print("=================================================")
print("             PLINUX INSTALLER")
print("=================================================")
print("Welcome to plinux installer ! wait 5 seconds")
print("If you do want to no install plinux PRESS CTRL T or restart computer")
print("=================================================")
sleep(5)
shell.run("clear")
shell.run("mkdir home")
shell.run("mkdir var")
shell.run("mkdir home/music")
shell.run("mkdir app")
shell.run("mkdir home/Downloads")
shell.run("mkdir os")
shell.run("mkdir os/screensaver")


shell.run("pastebin get bj3qj1Pj app/strafe")
shell.run("pastebin get J8azvLQg os/screensaver/WhereIsDan")


shell.run("pastebin get A7wGH3ty app/firewolf")
shell.run("pastebin get yjKf6pHN app/terminal")
shell.run("pastebin get 0wkqTE1A os/calc")
sleep(1)
shell.run("clear")
shell.run("wget https://raw.githubusercontent.com/EletrixtimeYT/PlinuxOS/main/startup.lua startup")
shell.run("wget https://raw.githubusercontent.com/EletrixtimeYT/PlinuxOS/main/os/main.lua os/main.lua")
shell.run("clear")
print("=================================================")
print("Exiting !")
print("=================================================")
os.reboot()
