shell.run("clear")
shell.run("mkdir home")
shell.run("mkdir var")
shell.run("mkdir home/music")
shell.run("mkdir app")
shell.run("mkdir home/Downloads")
shell.run("mkdir var/screensaver")
shell.run("mkdir os")
print("Plinux Created File OK")

print("Downloading APP")
print("Downloading Strafe")
shell.run("pastebin get bj3qj1Pj app/strafe")
print("Finised download STRAFE")
print("Downloading WhereIsDan")
shell.run("pastebin get J8azvLQg var/screensaver/WhereIsDan")

print("Downloading FireWolf Browser")
shell.run("pastebin get A7wGH3ty app/firewolf")
shell.run("pastebin get yjKf6pHN app/terminal")
shell.run("pastebin get 0wkqTE1A os/calc")
sleep(1)
print("Downloading STARTUP.LUA")
shell.run("wget https://raw.githubusercontent.com/EletrixtimeYT/PlinuxOS/main/startup.lua startup")
shell.run("wget https://raw.githubusercontent.com/EletrixtimeYT/PlinuxOS/main/main.lua os/main.lua")
shell.run("clear")
print("Exiting !")
os.reboot()
